package com.androidlabs.adapter

import androidx.room.Dao
import com.androidlabs.util.StaticMethods
import androidx.room.Update
import androidx.room.Delete
import com.androidlabs.data.entity.Calculations
import androidx.room.PrimaryKey
import android.content.ContentValues
import androidx.room.Database
import androidx.room.RoomDatabase
import com.androidlabs.data.dao.FigureDao
import com.androidlabs.data.dao.CalculationsDAO
import com.androidlabs.data.dao.DataDao
import com.androidlabs.data.AppDatabase
import com.androidlabs.util.App
import androidx.room.Room
import androidx.recyclerview.widget.RecyclerView
import com.androidlabs.adapter.FiguresAdapter.FiguresViewHolder
import android.view.ViewGroup
import android.view.LayoutInflater
import com.androidlabs.R
import androidx.navigation.Navigation
import android.widget.TextView
import android.widget.ImageButton
import com.androidlabs.adapter.HistoryAdapter.HistoryViewHolder
import android.content.SharedPreferences
import android.os.Bundle
import com.androidlabs.provider.MyContentProvider
import org.decimal4j.util.DoubleRounder
import android.content.ContentUris
import android.widget.LinearLayout
import android.widget.ArrayAdapter
import android.widget.AdapterView.OnItemSelectedListener
import android.widget.AdapterView
import android.widget.EditText
import androidx.appcompat.app.AppCompatActivity
import com.google.android.material.navigation.NavigationView
import androidx.drawerlayout.widget.DrawerLayout
import androidx.navigation.NavController
import androidx.navigation.ui.NavigationUI
import android.content.SharedPreferences.Editor
import com.google.android.material.snackbar.Snackbar
import android.view.Gravity
import com.androidlabs.adapter.FiguresAdapter
import com.androidlabs.adapter.HistoryAdapter
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout.OnRefreshListener
import android.text.TextUtils
import kotlin.jvm.Throws
import org.apache.commons.csv.CSVParser
import org.apache.commons.csv.CSVFormat
import org.apache.commons.csv.CSVRecord
import androidx.preference.PreferenceFragmentCompat
import android.content.ContentProvider
import android.content.UriMatcher
